global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: cadvisor
    dns_sd_configs:
      - names: ['tasks.cadvisor']
        type: A
        port: 8080

  - job_name: haproxy_exporter
    dns_sd_configs:
      - names: ['tasks.haproxy_exporter']
        type: A
        port: 9101

  - job_name: haproxy
    dns_sd_configs:
      - names: ['tasks.openslide_haproxy-lb']
        type: A
        port: 8404
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        replacement: openslide_haproxy-lb:8404

      - target_label: instance
        replacement: openslide_haproxy-lb:8404
