version: "3.8"

services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"        # Kafka external port
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      # Listener config (INSIDE = untuk container internal, OUTSIDE = untuk client luar container)
      KAFKA_LISTENERS: "INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "INSIDE://kafka:9092,OUTSIDE://46.250.229.129:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INSIDE"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-ui:
    image: provectuslabs/kafka-ui:latest  # Kafka UI dashboard
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080" # Web UI accessible at http://localhost:8090
    environment:
      KAFKA_CLUSTERS_0_NAME: "kafka-local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"

